# Generated by Django 5.1.6 on 2025-03-14 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('telf_number', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('fantasy', 'Fantasy'), ('science_fiction', 'Science Fiction'), ('mystery_thriller', 'Mystery/Thriller'), ('romance', 'Romance'), ('horror', 'Horror'), ('history', 'History'), ('biography_memoir', 'Biography/Memoir'), ('philosophy', 'Philosophy'), ('self_help', 'Self-Help'), ('science_technology', 'Science & Technology')], max_length=20)),
                ('language', models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English'), ('others', 'Others')], max_length=10)),
                ('author', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('format', models.CharField(choices=[('ebook', 'eBook'), ('physical', 'Physical Book'), ('audiobook', 'AudioBook')], max_length=15)),
                ('age_range', models.CharField(choices=[('children', 'Children'), ('young_adult', 'Young Adult'), ('adult', 'Adult')], max_length=15)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app.library')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='app.user')),
            ],
        ),
    ]
